# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request, push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install pip
        run: |
          python -m pip install --upgrade pip

      - name: install conan
        run: |
          pip install conan          

      - name: nmos test
        run: |
          git clone https://github.com/AMWA-TV/nmos-testing/
          cd nmos-testing
          pip install cryptography --upgrade
          pip install -r requirements.txt
          python nmos-test.py --help

      - name: setup tmate
        uses: mxschmitt/action-tmate@v2
        if: runner.os == 'macOS' && false
